history01/urls.py
# from django.contrib import admin
from django.urls import path,re_path
from app01 import views
# from django.views.static import serve
# from django.conf import settings

urlpatterns = [
    # re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}, name='media'),      #配置media
#    path('admin/', admin.site.urls),
#     path('test/', views.test),  # 测试页面
    #re_path(r'^$',views.home),

    #基本页面
    path('home/', views.home),      #主页
    path('', views.home),      #主页
    path('signIn/', views.signIn),  #注册
    path('login/', views.login),    #登录
    path('send_sms_code/', views.signin_check),    # 在注册界面发送验证邮件
    path('image/code/', views.image_code),  # 在登录界面生成图片验证码
    path('image/refresh/', views.image_refresh),  # 刷新验证码
    path('forgot/pwd/', views.forgot_pwd),  # 忘记密码
    path('forgot/pwd/code/', views.forgot_pwd_code),  # 忘记密码界面发送邮箱验证码
    path('contact_us/', views.contact_us),  # 联系我们


    #论坛
    path('forum/<int:category>/category/',views.forum_main),    #论坛主页
    path('forum/post/',views.forum_post),    #发布帖子
    path('forum/<int:psg_id>/passage/',views.forum_passage),    #论坛-查看帖子
    path('forum/<int:psg_id>/delete/',views.forum_delete),    #论坛-删除帖子
    path('forum/<int:user_id>/author/',views.forum_author),    #论坛-个人主页



    #纪念馆
    #path('museum/', views.museum),  # 纪念馆
    path('museum/log/', views.museum_log),  # 更新日志
    path('museum/about_us/', views.museum_about_us),  # 关于我们
    # path('museum/agreements/', views.museum_agreements),  # 协议



    #账户管理
    path('account/', views.account),    #账户管理
    path('edit/<int:id>/account/', views.edit_account),    #修改账户信息
    path('write_off/account/', views.write_off),    #注销账户
    path('quit/account/', views.quit_account),    #注销账户


    # #二班史册
    # path('history/content/', views.history_main),    #二班史册 主页
    # path('history/login/', views.history_login),    #二班史册 登录页
    # path('history/overview/content/', views.history_overview),    #二班史册 内容 概述
    # path('history/<int:chapter>/<int:section>/content/', views.history_frame),    #二班史册 内容 章节

    #管理员方可访问的页面
    path('admin/main/', views.admin_main),  # 管理员 面板
    path('admin/login/', views.admin_login),  # 管理员 面板
    path('admin/user_list/', views.admin_user_list),      #用户管理
    path('admin/<int:id>/user_delete/', views.admin_user_delete),      #编辑用户
    path('admin/<int:id>/user_edit/', views.admin_user_edit),      #删除用户
    path('admin/log/', views.admin_log),  # 日志管理
    path('admin/creat_log/', views.admin_creat_log),  # 日志管理
    path('admin/<int:id>/log_edit/', views.admin_log_edit),  # 编辑日志
    path('admin/<int:id>/log_delete/', views.admin_log_delete),  # 删除日志
    path('admin/<int:content_type>/forum/',views.admin_forum),     #论坛管理    1-待审核帖子；2-已发布帖子；3-待审核评论；4-已发布评论
    path('admin/forum/<int:psg_id>/<int:access>/psg/',views.admin_forum_psg),  #论坛管理-审核是/否通过     0-未通过；1-通过
    #path('admin/forum/passage/released/',views.admin_forum_passage_released),     #论坛管理=管理已发布帖子



    #path('signIn/', views.signIn),  #评论管理
    #path(r"^$",views.home),


    #path('editor/', views.md, name='editor'),

    # # 在线markdown
    # path('md/<int:user_id>/<int:file_id>/edit/',views.md_edit, name='markdown'),       #编辑文件
    # path('md/<int:id>/files/',views.md_files),       #管理文件
    # path('md/<int:user_id>/<int:obj_id>/delete/', views.md_delete),  # 删除
    # path('md/<int:user_id>/<int:obj_id>/rename/', views.md_rename),  # 重命名
    # path('md/<int:user_id>/<int:obj_id>/download/', views.md_download),  # 下载
    # path('md/upload/',views.md_upload),       #上传文件

    # re_path(r'^$',views.home),
]

app01/models.py
from django.db import models

# Create your models here.
class UserInfo(models.Model):
    '''用户信息'''
    name = models.CharField(verbose_name="用户名",max_length=7)
    email = models.CharField(verbose_name="邮箱",max_length=128)
    password = models.CharField(verbose_name="密码",max_length=64)
    write_off_choices = (
        (1,'已注销'),
        (2,'未注销'),
    )
    if_write_off = models.SmallIntegerField(verbose_name="是否已经注销",choices = write_off_choices,default=2)    #已经注销，值为1，没有注销为2，默认为2
    last_login = models.DateTimeField(verbose_name="上次登录时间", auto_now=True)




class Log(models.Model):
    '''更新日志'''
    version_num = models.CharField(verbose_name="版本号",max_length=64)
    publishTime = models.DateTimeField(verbose_name="时间", auto_now=False,auto_now_add=True)
    substance = models.TextField(verbose_name="内容",max_length=1024)
    developer_choices = (
        (1, 'wezy'),
        (2, 'other（待完善）'),
    )
    developer = models.SmallIntegerField(verbose_name="开发者",choices=developer_choices,default=1)



class Forum(models.Model):
    '''论坛帖子'''
    title = models.CharField(verbose_name="标题",max_length=64)
    content = models.TextField(verbose_name="内容",max_length=2048)
    user = models.IntegerField(verbose_name="所属用户id")   #用于和userInfo表关联
    publishDate = models.DateTimeField(verbose_name="发布时间", auto_now=True)
    category_choices = (    #所属板块
        (1, '公告'),
        (2, '推荐'),
        (3, '最新'),
        (4, '热门'),
    )
    category = models.SmallIntegerField(verbose_name="所属板块",choices=category_choices,default=3)
    status_choices = {
        (1, '待审核'),
        (2, '审核通过'),
        (3, '审核未通过'),
        (4, '已删除'),
    }
    status = models.SmallIntegerField(verbose_name="状态",choices=status_choices,default=1)


class ForumComments(models.Model):
    '''论坛评论'''
    user = models.IntegerField(verbose_name="所属用户id")  # 用于和userInfo表关联
    content = models.TextField(verbose_name="内容",max_length=1024)
    publishDate = models.DateTimeField(verbose_name="发布时间", auto_now=True)
    passage_id = models.IntegerField(verbose_name="所属帖子id")   #用于和forum表关联
    status_choices = {
        (1, '待审核'),
        (2, '审核通过'),
        (3, '审核未通过'),
        (4, '已删除'),
    }
    status = models.SmallIntegerField(verbose_name="状态",choices=status_choices,default=1)

app01/views.py
import json
from io import BytesIO
# import sys
# import time
from datetime import datetime
# import os
# import re  # 正则表达式

from django.shortcuts import render, HttpResponse, redirect
# from django.http import JsonResponse, FileResponse
from django.views.decorators.csrf import csrf_exempt
# from django.views.decorators.clickjacking import xframe_options_exempt
# from django.conf import settings
# from django.contrib import messages

from app01 import models
from app01.utils.create_code import check_code
from app01.utils.send_email import send_sms_code
from app01.utils.pagination import Pagination
from app01.utils.form import UserModelForm_signIn, UserModelForm_login, UserModelForm_edit_account, \
    UserModelForm_changePwd, UserModelForm_Log
# from app01.utils.form import LoginForm,CreateBugForm
from app01.utils.form import LoginForm,ForumForm,ForumCommentForm

# '''测试函数'''
# def test(request):
#     # send_sms_code()
#     return render(request,'test.html')


'''联系我们'''
def contact_us(request):
    return render(request, 'contact_us.html')


'''主页'''
def home(request):
    return redirect('/forum/0/category/')


'''注册'''
def signIn(request):
    if request.method == "GET":
        form = UserModelForm_signIn()
        return render(request, 'signIn.html', {"form": form})

    # 用户POST提交数据，进行数据校验
    form = UserModelForm_signIn(data=request.POST)
    get_verify = request.POST.get("verify")  # 获取用户输入的验证码
    verification_code = request.session.get('text_code', "")  # 获取存在session中的验证码
    if form.is_valid():  # 如果数据合法，保存到数据库
        if get_verify == verification_code:  # 如果验证码正确
            form.save()
            return redirect('/login/')
        else:
            return render(request, "signIn.html", {"form": form, "msg_warn": "邮箱验证码错误！"})

    # 校验失败，显示错误信息
    return render(request, 'signIn.html', {"form": form})


'''注册-验证数据合法性并调用发送邮件的函数'''
@csrf_exempt
def signin_check(request):
    form = UserModelForm_signIn(data=request.POST)
    # print(form)

    if form.is_valid():
        # 判断邮箱是否已经被注册过，数据库中是否已经存在数据
        choise = models.UserInfo.objects.filter(email=request.POST.get("email")).exists()

        # 如果choise==true，说明数据库已经存在这个邮箱
        if choise:
            # 获取这条数据的内容，判断是否已经被注销
            datalist = models.UserInfo.objects.filter(email=request.POST.get("email")).last()  # 获取最新数据
            if datalist.if_write_off == 1:  # 存在数据，但是那个账号已经被注销，也可以注册
                datas = form.save(commit=False)  # 获取用户已经输入的数据，但是不存入数据库，用作发送邮件
                to_email = datas.email
            else:
                dict = {"msg_warn": "邮箱已经被注册过！"}
                return HttpResponse(json.dumps(dict))
        else:  # 不存在信息，可以注册，发送验证邮件
            datas = form.save(commit=False)  # 获取用户已经输入的数据，但是不存入数据库，用作发送邮件
            to_email = datas.email
    else:
        data_dict = {'error': form.errors}
        return HttpResponse(json.dumps(data_dict, ensure_ascii=False))

    print(to_email)
    verification_code = send_sms_code(to_email)

    # 写入到自己的session中，方便后续获取验证码进行校验
    request.session['text_code'] = verification_code
    # 给session设置二十分钟超时,超出二十分钟后获取不到
    session_time = 60 * 20
    request.session.set_expiry(session_time)
    print(verification_code)

    dicti = {"msg_success": "邮箱验证码发送成功！"}
    return HttpResponse(json.dumps(dicti))


'''登录'''
def login(request):
    if request.method == "GET":
        form = LoginForm()
        return render(request, 'login.html', {'form': form})

    form = LoginForm(data=request.POST)
    if form.is_valid():
        # 获取用户输入的验证码，并从cleaned_data中去除掉以防止影响数据库的判断
        user_input_code = form.cleaned_data.pop('code')
        code = request.session.get(
            'image_code')  # 在这里，如果在图片验证码那个函数里设置了session的过期时间，则要写为code = request.session.get('image_code', "")
        if code.upper() != user_input_code.upper():
            form.add_error("code", "验证码错误！")
            return render(request, 'login.html', {'form': form})

        # 去数据库校验数据是否正确
        admin_object = models.UserInfo.objects.filter(**form.cleaned_data).last()  # 校验是否存在这条数据，而且能获取到的包含已经注销的用户
        datalist = models.UserInfo.objects.filter(
            email=form.cleaned_data['email']).last()  # 获取邮箱为email的最新数据的所有内容，用于下一步判断是否已经注销
        if (not admin_object) or (datalist.if_write_off == 1):
            # 邮箱或者密码不正确(不存在数据) or 账户已经注销
            form.add_error("password", "邮箱或密码错误！")
            return render(request, 'login.html', {'form': form})

        # 邮箱和密码正确，获取当前登录的用户的ID，存储到session中
        # 用户名和密码都正确，生成随机字符串，写入到用户浏览器的cookie中，再写入到session中（此处session为一个字典）
        request.session["info"] = {"id": admin_object.id, 'email': admin_object.email, 'name': admin_object.name}
        keep_time = 5 * 24 * 60 * 60
        request.session.set_expiry(keep_time)  # 设置session过期时间为5天

        # datalist.update(last_login=datetime.datetime())
        models.UserInfo.objects.filter(email=form.cleaned_data['email']).update(last_login=datetime.now())
        return redirect('/home/')

    return render(request, 'login.html', {'form': form})


'''生成图片验证码'''
@csrf_exempt
def image_code(request):
    # 调用生成图片验证码的函数
    img, code_str = check_code()
    print("验证码为" + code_str)

    # 写入到自己的session中，方便后续获取验证码进行校验
    request.session['image_code'] = code_str
    # 给session设置120s超时,超出120s后获取不到
    # request.session.set_expiry(120)

    # 把生成的图片写入内存中
    stream = BytesIO()
    img.save(stream, 'png')
    return HttpResponse(stream.getvalue())


'''点击图片刷新验证码-Ajax'''
@csrf_exempt
def image_refresh(request):
    # 调用生成图片验证码的函数
    img, code_str = check_code()
    print("验证码为" + code_str)

    # 写入到自己的session中，方便后续获取验证码进行校验
    request.session['image_code'] = code_str
    # 给session设置120s超时,超出120s后获取不到
    request.session.set_expiry(120)

    # 把生成的图片写入内存中
    stream = BytesIO()
    img.save(stream, 'png')
    return HttpResponse(stream.getvalue(), content_type='image/png')


'''账户管理'''
def account(request):
    info = request.session.get("info")
    nid = info['id']
    email = info['email']
    queryset = models.UserInfo.objects.filter(email=email).last()  # 从数据库获取当前用户的对象
    # nid = queryset.id
    return render(request, 'account.html', {"queryset": queryset})


'''编辑信息'''
def edit_account(request, id):
    info = request.session.get("info")
    nid = info['id']
    email = info['email']

    row_object = models.UserInfo.objects.filter(id=nid).first()  # 如果能获取到，返回一个对象；获取不到返回None
    # 如果是none，则返回错误页面
    if not row_object:
        return render(request, '404.html')

    # print(email)
    # row_object = models.UserInfo.objects.filter(email=email).last()        #从数据库获取email为n_email的对象
    if request.method == "GET":
        form = UserModelForm_edit_account(instance=row_object)
        return render(request, 'account_edit.html', {"form": form})

    # 用户POST提交数据，进行数据校验
    form = UserModelForm_edit_account(data=request.POST, instance=row_object)
    if form.is_valid():
        # 如果数据合法，保存到数据库
        form.save()
        # 这里还可以优化：从用户提交的请求中获取数据，但是我现在没法查资料，不知道怎么写，先放这
        print(form.cleaned_data["name"])

        # 更新session
        email = form.cleaned_data["email"]
        id = models.UserInfo.objects.filter(email=email).last().id  # 由于用户提交的数据里没有ID，所以得先从数据库中获取用户的id
        request.session["info"] = {'id': id, 'email': email, 'name': form.cleaned_data["name"]}
        return redirect('/account/')

    # 校验失败，显示错误信息
    return render(request, 'account_edit.html', {"form": form})


'''退出登录'''
def quit_account(request):
    request.session.clear()
    return redirect('/home/')


'''注销'''
def write_off(request):
    info = request.session.get("info")
    nid = info['id']
    print(nid)
    models.UserInfo.objects.filter(id=nid).update(if_write_off=1)
    # models.UserInfo.objects.filter(id=nid).delete()
    request.session.clear()
    return redirect('/login/')


'''忘记密码'''
def forgot_pwd(request):
    if request.method == "GET":
        form = UserModelForm_changePwd()
        return render(request, 'forgot_pwd.html', {"form": form})

    form = UserModelForm_changePwd(data=request.POST)
    get_verify = request.POST.get("verify")  # 获取用户输入的验证码
    verification_code = request.session.get('retrieve_code', "")  # 获取存在session中的验证码

    if get_verify == verification_code:  # 如果验证码正确
        # request.session['pwd_change_email'] = request.POST.get("email")    #将要修改的邮箱写入session，便于后面调用
        if form.is_valid():
            models.UserInfo.objects.filter(email=form.cleaned_data["email"]).update(
                password=form.cleaned_data["password"])  # 修改数据库中的密码
            return redirect('/login/')  # 跳转到登录
        return render(request, 'forgot_pwd.html', {"form": form})
    else:
        return render(request, "forgot_pwd.html", {"form": form, "msg_warn": "邮箱验证码错误！"})


'''忘记密码-验证邮箱和发送邮件'''
@csrf_exempt
def forgot_pwd_code(request):
    # POST提交数据进行处理
    form = UserModelForm_changePwd(data=request.POST)
    # if form.is_valid():

    # 判断邮箱是否已经被注册过，数据库中是否已经存在数据
    choise = models.UserInfo.objects.filter(email=request.POST.get("email")).exists()
    if choise:
        datalist = models.UserInfo.objects.filter(email=request.POST.get("email")).last()  # 获取最新数据
        if datalist.if_write_off == 1:  # 存在数据，但是那个账号已经被注销，不能找回
            dict = {"msg_warn": "邮箱不存在！"}
            return HttpResponse(json.dumps(dict))
        else:
            to_email = datalist.email
            print(to_email)

    else:  # 数据库不存在该邮箱
        dict = {"msg_warn": "邮箱不存在！"}
        return HttpResponse(json.dumps(dict))

    # 邮箱校验成功，发送邮件
    verification_code = send_sms_code(to_email)
    # 写入到自己的session中，方便后续获取验证码进行校验
    request.session['retrieve_code'] = verification_code
    # 给session设置二十分钟超时,超出二十分钟后获取不到
    session_time = 60 * 20
    request.session.set_expiry(session_time)
    print(verification_code)

    dict = {"msg_success": "邮箱验证码发送成功！"}
    return HttpResponse(json.dumps(dict))



'''只有管理员可访问的url'''
'''管理员-面板'''
def admin_main(request):
    return render(request, 'admin_main.html')


'''管理员-登入'''
def admin_login(request):

app01/templates/account.html
{% extends 'layout.html' %}
{% block content %}
    <title>账户管理</title>
    <script>
        function alert() {
            var x;
            var r = confirm("确定要注销账号吗？这将删除你的的所有信息！");
            if (r == true) {
                window.location.href = "/write_off/account/";
            }
        }
    </script>

{#    <div>#}
{##}
{#        <form method="post" novalidate class=".form-group"#}
{#              style="position: absolute; width: 50%;top: 40%; left: 50%; transform: translate(-50%,-50%);">#}
{#            <h3>我的账户</h3>#}
{##}
{#            <table class="table table-bordered" style="width: 250%" ;>#}
{#                <thead>#}
{#                <tr>#}
{#                    <th>ID</th>#}
{#                    <th>昵称</th>#}
{#                    <th>邮箱</th>#}
{#                    <th>密码</th>#}
{#                    <th>操作</th>#}
{#                </tr>#}
{#                </thead>#}
{##}
{#                <tr>#}
{#                    <th>{{ queryset.id }}</th>#}
{#                    <td>{{ queryset.name }}</td>#}
{#                    <td>{{ queryset.email }}</td>#}
{#                    <td>{{ queryset.password }}</td>#}
{##}
{#                    <td>#}
{#                        <!--<a class="btn btn-primary btn-xs" href="#">编辑</a>-->#}
{#                        <a href="/edit/{{ queryset.id }}/account/" class="btn btn-primary btn-sm">编辑信息</a>#}
{#                        <a href="" class="btn btn-primary btn-sm">评论管理</a>#}
{#                        <a href="/quit/account/" class="btn btn-warning btn-sm">退出登录</a>#}
{#                        <a onclick="alert()" class="btn btn-danger btn-sm">注销账户</a>#}
{#                        <!--<button onclick="alert()" class="btn btn-danger btn-sm">注销账户</button>-->#}
{##}
{#                    </td>#}
{#                </tr>#}
{#            </table>#}
{#            <a href="/home/" class="btn btn-default">返回</a>#}
{#        </form>#}
{#    </div>#}
      <div class="container">
    <h3 class="text-center">个人信息</h3>
    <div class="table-responsive">
      <table class="table table-bordered table-striped">
        <tbody>
          <tr>
            <td class="info-label">昵称</td>
            <td>{{ queryset.id }}</td>
          </tr>
          <tr>
            <td class="info-label">邮箱</td>
            <td>{{ queryset.email }}</td>
          </tr>
          <tr>
            <td class="info-label">密码</td>
            <td>{{ queryset.password }}</td>
          </tr>
        </tbody>
      </table>
        <!--<a class="btn btn-primary btn-xs" href="#">编辑</a>-->
            <a href="/edit/{{ queryset.id }}/account/" class="btn btn-primary btn-sm">编辑信息</a>
            <a onclick="alert()" class="btn btn-danger btn-sm">注销账户</a>
            <!--<button onclick="alert()" class="btn btn-danger btn-sm">注销账户</button>-->
    </div>
  </div>
{% endblock %}

app01/templates/admin_edit.html
{% extends 'admin_layout.html' %}
{% block content %}

    <title>{{ title }}</title>
    <div>
        <form method="post" novalidate class=".form-group"
              style="position: relative; width: 50%;top: 250px; left: 50%; transform: translate(-50%,-50%);">
            <h3>{{ title }}</h3>
            {% csrf_token %}
            {% for field in form %}
                <div class="form-group">
                    <label for="exampleInputEmail1">{{ field.label }}</label>
                    {{ field }}
                    <span style="color: red;">{{ field.errors.0 }}</span>
                    <!--<input name="name" type="email" class="form-control" id="exampleInputEmail1" placeholder="Name">-->
                </div>
            {% endfor %}

            <button type="submit" class="btn btn-default">提交修改</button>
            <a href="/admin/main/" class="btn btn-default">返回</a>
        </form>

    </div>

{% endblock %}

app01/templates/admin_forum_passage_released.html
{% extends 'admin_layout.html' %}
{% block content %}
    <section class="mt-4 mb-5">
        <div class="container mb-4">
            <div>
                {% for obj in queryset %}
                    <div class="list-group-item-main">
                        <a href="/forum/{{ obj.id }}/passage/">
                            <div class="list-group-item">
                                <a href="/forum/{{ obj.id }}/delete/">
                                    <button style="float: right" type="button" class="btn btn-danger">删除</button>
                                </a>
                                <h4 class="list-group-item-heading">{{ obj.title }}</h4>
                                <small>{{ obj.username }} &nbsp&nbsp{{ obj.publishDate }}</small>
                                <p class="list-group-item-text">{{ obj.content }}</p>
                            </div>
                        </a>
                    </div>
                    <br>
                {% endfor %}

                <div class="clearfix"><!--分页组件-->
                    <ul class="pagination">
                        {{ page_string }}
                    </ul>
                </div>
            </div>
        </div>
        </main>

        </div>
    </section>

{% endblock %}

app01/templates/admin_log.html
{% extends 'admin_layout.html' %}
{% block content %}
    <title>日志管理</title>
    <div class="col-md-4">
        <div class="container">

            <div style="margin-bottom: 10px">
                <a class="btn btn-success" href="/admin/creat_log/">
                    <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
                    新建日志
                </a>

            </div>
            <div class="panel panel-default">
                <!-- Default panel contents -->
                <div class="panel-heading">
                    <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                    日志管理
                </div>

                <!-- Table -->
                <table class="table table-bordered">
                    <thead>
                    <tr>
                        <th>ID</th>
                        <th>版本号</th>
                        <th>时间</th>
                        <th>内容</th>
                        <th>开发者</th>
                        <th>操作</th>
                    </tr>
                    </thead>
                    {% for obj in queryset %}

                        <tbody>
                        <tr>
                            <td>{{ obj.id }}</td>
                            <td>{{ obj.version_num }}</td>
                            <td>{{ obj.publishTime }}</td>
                            <td>{{ obj.substance|linebreaksbr }}</td>
                            <td>{{ obj.get_developer_display }}</td>
                            <td>
                                <a href="/admin/{{ obj.id }}/log_edit/" class="btn btn-primary btn-xs" href="#">编辑</a>
                                <a href="/admin/{{ obj.id }}/log_delete/" class="btn btn-danger btn-xs">删除</a>
                                <!--<a href="/quit/account/" class="btn btn-warning btn-sm">退出登录</a>-->
                            </td>
                        </tr>
                    {% endfor %}

                    </tbody>
                </table>
            </div>
            <div class="clearfix">
                <ul class="pagination">
                    {{ page_string }}
                </ul>
            </div>
        </div>

    </div>
{% endblock %}

app01/templates/admin_log_creat.html
{% extends 'admin_layout.html' %}
{% block content %}
    {% load static %}
    <title>新建日志</title>
    <div style="position: relative; width: 50%;top: 250px; left: 50%; transform: translate(-50%,-50%);">
        <form id="biao_dan" method="post" novalidate class=".form-group">
            <!--<form id="biao_dan" action="/send_sms_code/" method="post" novalidate class=".form-group" style="position: absolute; width: 50%;top: 40%; left: 50%; transform: translate(-50%,-50%);">-->
            <h3>新建日志</h3>
            {% csrf_token %}
            {% for field in form %}
                <div class="form-group" style="position: relative;">
                    <label for="exampleInputEmail1">{{ field.label }}</label>
                    {{ field }}
                    <span style="color: red;" class="error_msg" style="position: absolute;"></span>
                    <!--<input name="name" type="email" class="form-control" id="exampleInputEmail1" placeholder="Name">-->
                </div>
            {% endfor %}
            <!--<button type="submit" onclick="change_action()" class="btn btn-default">提交</button>-->
            <input type="submit" id="submit_btn" class="btn btn-default">
        </form>
    </div>

{% endblock %}
{% block js %}

{% endblock %}

app01/templates/forum_myself.html
{% extends 'forum_layout.html' %}
{% block content %}
    <title>我的主页</title>
    <section class="mt-4 mb-5">
        <div class="container mb-4">
            <h2 class="font-weight-bold title">我的主页</h2>
            <a href="/account/" class="btn btn-outline-secondary">个人信息</a>
            <a href="/account/" class="btn btn-outline-secondary">退出登录</a>
            <p><!--个签--></p>

            <div>
                {% for obj in queryset %}
                    <div class="list-group-item-main">
                        <div class="list-group-item">
                            <a style="float: right" class="btn btn-outline-danger" href="/forum/{{ obj.id }}/delete/">
                                删除
                            </a>
                            <a href="/forum/{{ obj.id }}/passage/">
                                <span href="#" class="badge badge-secondary">{{ obj.get_status_display }}</span>
                                <h4 class="list-group-item-heading">{{ obj.title }}</h4>
                                <small>{{ obj.username }} &nbsp&nbsp{{ obj.publishDate }}</small>
                                <p class="list-group-item-text">{{ obj.content }}</p>
                            </a>
                        </div>

                    </div>
                    <br>
                {% endfor %}

                <div class="clearfix"><!--分页组件-->
                    <ul class="pagination">
                        {{ page_string }}
                    </ul>
                </div>
            </div>
        </div>


        </main>

        </div>
    </section>
    <script>
    function click(){
        console.log("1")
    }
    </script>

{% endblock %}

app01/templates/museum_log.html
{% extends 'layout.html' %}
{% block content %}
    <title>日志管理</title>
    <br><br>
    <div class="col-md-4">
        <div class="container">
            <div class="panel panel-info">
                <!-- Default panel contents -->
                <div class="panel-heading">
                    <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                    更新日志
                </div>

                <!-- Table -->
                <table class="table table-bordered">
                    <thead>
                    <tr>
                        <th>版本号</th>
                        <th>时间</th>
                        <th>内容</th>
                        <th>开发者</th>
                    </tr>
                    </thead>
                    {% for obj in queryset %}

                        <tbody>
                        <tr>
                            <td>{{ obj.version_num }}</td>
                            <td>{{ obj.publishTime }}</td>
                            <td>{{ obj.substance|linebreaksbr }}</td>
                            <td>{{ obj.get_developer_display }}</td>
                        </tr>
                    {% endfor %}

                    </tbody>
                </table>
            </div>
            <div class="clearfix">
                <ul class="pagination">
                    {{ page_string }}
                </ul>
            </div>
            <a class="btn btn-default" href="/forum/0/category">返回</a>
        </div>
    </div>
{% endblock %}